### ISSUE TITLE
StyleAvatar takes too long to train

### ISSUE THREAD

**Issue by movingright** [LizhenWangT/StyleAvatar#15]
Thanks for the great repo.

I'm training the Full StyleAvatar, specifically with the command `python train.py --batch 3 path-to-dataset`. Training from scratch as the checkpoints have not been shared yet. 

On the A10 GPU, it takes about a week to run for the default training parameters. Is that normal? I ask because the paper mentioned 
> The proposed network can converge within two hours while ensuring high image quality and a forward rendering time of only 20 milliseconds.

So maybe I'm missing something, can you help? :)

**Comment by LizhenWangT** [comment]
Just stop when the generated image meets your requirements (several hours). Don't care about the default steps.

**Comment by movingright** [comment]
Thanks for the prompt response, I trained it for 17 hours for 65,000 timesteps, and this is the result. While the individual frame quality is good, the video flickers a lot. Any ideas on why that might be the case? 

https://github.com/LizhenWangT/StyleAvatar/assets/139023272/dd9312fd-358b-478b-937e-e27bffad66f4

**Comment by movingright** [comment]
The command I used to generate these results is: `python test.py --render_dir ../../FaceVerse/faceversev3_jittor/output/video/render --uv_dir ../../FaceVerse/faceversev3_jittor/output/video/uv --ckpt logs/checkpoint/video_065000.pt --save_dir output`

This is already running with --batch 1 as that's the default setting: `https://github.com/LizhenWangT/StyleAvatar/blob/main/styleavatar/test.py#L39`

What else could be the reason? @LizhenWangT

**Comment by movingright** [comment]
Could you clarify what you mean by “input render folder”? 

Currently, I’m using the same folder (which is ‘ ../../FaceVerse/faceversev3_jittor/output’ in my case) for both train.py and test.py.

**Comment by movingright** [comment]
My bad, ignore my previous message, I understood what you mean now. Here's the input render video you requested for (attached first 800 frames only). It flickers as you expected. Does this mean it's an issue with how I'm preprocessing my data? Thanks again for your continual help. @LizhenWangT 

https://github.com/LizhenWangT/StyleAvatar/assets/139023272/6208aab1-d604-472c-9244-ee34f6c5f354

**Comment by LizhenWangT** [comment]
Thank you. I think the input video is normal. Compared with the paper version, I need to optimize the code readability, so I made some modification. It hasn't been extensively tested, especially the python preprocessing version. Please wait a few days i will test this video.

**Comment by movingright** [comment]
Sure, thanks @LizhenWangT  :)

**Comment by LizhenWangT** [comment]
Fixed now. It was mainly caused by the flickering tracking of FaceVerse. Smooth term in preprocessing has been updated. The pretrained model uploaded can perform like this:

https://github.com/LizhenWangT/StyleAvatar/assets/26791093/a4ac5f63-6b7b-47da-baca-97092a0d2025

**Comment by movingright** [comment]
Thank you, I’ll test this and confirm. @LizhenWangT

**Comment by movingright** [comment]
I get the following error:
```
Compiling Operators(8/8) used: 3.31s eta:    0s 
Traceback (most recent call last):
  File "tracking_offline_cuda.py", line 221, in <module>
    tracking = Tracking(args)
  File "tracking_offline_cuda.py", line 30, in __init__
    self.offreader = OfflineReader(args.input, args.back, args.tar_size, args.image_size, args.crop_size, skip_frames=args.skip_frames)
TypeError: __init__() got multiple values for argument 'skip_frames'
```

Looks like you might have forgotten to update the OfflineReader class? @LizhenWangT 
https://github.com/LizhenWangT/FaceVerse/blob/main/faceversev3_jittor/data_reader.py#L119

**Comment by LizhenWangT** [comment]
Thank you for the message. This bug has been fixed now.

**Comment by movingright** [comment]
For some reason, my render still flickers, even though I'm using the latest version of https://github.com/LizhenWangT/FaceVerse/blob/main/faceversev3_jittor/. Any ideas on why that might be the case? @LizhenWangT 

https://github.com/LizhenWangT/StyleAvatar/assets/139023272/87153dea-0f10-4eb0-89a3-89354f074097

https://github.com/LizhenWangT/StyleAvatar/assets/139023272/943bcbe8-b594-4f9b-a8ec-2c1b0478da10

**Comment by LizhenWangT** [comment]
Please add `--smooth` for the pretraining if you need to test on the training video.

**Comment by movingright** [comment]
That's helpful, thanks @LizhenWangT. It works now. One final question, how many timesteps have you trained the pretrained checkpoints for?

**Comment by LizhenWangT** [comment]
About 10 hours, 90000 steps, batchsize=2.

**Comment by movingright** [comment]
Thank you! I'll retrain with the same parameters, and will let you know if I face any issues. @LizhenWangT

**Comment by LizhenWangT** [comment]
> Thank you! I'll retrain with the same parameters, and will let you know if I face any issues. @LizhenWangT

OK! You can also stop training earlier if you train a new model from this checkpoint.

**Comment by movingright** [comment]
Makes sense, thank you! @LizhenWangT

**Comment by Inferencer** [comment]
I'm at 75k timesteps after 8 hours using a 5 minute video, 
`!python train.py --batch 2 --ckpt /content/StyleAvatar/styleavatar/pretrained/lizhen_full_python.pt /content/StyleAvatar/styleavatar/ff`

```
load dataset: 0 ff
load model: /content/StyleAvatar/styleavatar/pretrained/lizhen_full_python.pt
  0% 0/800000 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py:3737: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
d: 0.0075; g: 5.9484; l1: 0.0947; vgg: 0.4637; mask: 0.0333 :  10% 76210/800000 [8:07:23<75:51:44,  2.65it/s]
```
![ff_076000](https://github.com/LizhenWangT/StyleAvatar/assets/121839197/a6e7dd5f-2a18-43ae-8c27-a81bba0f99ff)

results are poor so far

**Comment by LizhenWangT** [comment]
Actually, the training of styleunet is more stable than styleavatar. Sometimes the training of styleavatar may fail when the discriminator loss is always lower than 0.1 (`d: 0.0075; g: 5.9484;`), which means the discriminator is almost useless. Usually try to train the dataset for a second time from the first checkpoint may solve this problem (different random numbers of latent, noise, etc.).

**Comment by Inferencer** [comment]
> Actually, the training of styleunet is more stable than styleavatar. Sometimes the training of styleavatar may fail when the discriminator loss is always lower than 0.1 (`d: 0.0075; g: 5.9484;`), which means the discriminator is almost useless. Usually try to train the dataset for a second time from the first checkpoint may solve this problem (different random numbers of latent, noise, etc.).

You mean just re-run it? or train styleUnet model then train styleAvatar from the new styleUnet checkpoint

**Comment by LizhenWangT** [comment]
> > Actually, the training of styleunet is more stable than styleavatar. Sometimes the training of styleavatar may fail when the discriminator loss is always lower than 0.1 (`d: 0.0075; g: 5.9484;`), which means the discriminator is almost useless. Usually try to train the dataset for a second time from the first checkpoint may solve this problem (different random numbers of latent, noise, etc.).
> 
> You mean just re-run it? or train styleUnet model then train styleAvatar from the new styleUnet checkpoint

Yes, just re-run it from the checkpoint when you see the discriminator loss is always lower than 0.1.

**Comment by Fritskee** [comment]
@LizhenWangT Could you please elaborate a bit on the cross-person re-anactment. I did my driving video of input talker with faceverse so I have the renders and the uv masks. I also trained a model for 20k iterations on my target person. But I'm getting pretty bad results. 

Could you help me on my way with this:
`Details: As shown in Line 129-132 of FaceVerse/faceversev3_jittor/tracking_offline_cuda.py, you need to change the first 150 dims (shape parameters of another person) of the jittor tensor coeffs in Line 123 to the values (shape parameters of the source actor) in id.txt generated by FaceVerse/faceversev3_jittor/tracking_offline_cuda.py. If you are testing cross person re-enactment cases and only if the source actor's expression in the first frame is neutral expression, as shown in Line 133-134, add the first expression in exp.txt to the exp param (id and exp are coupling with each other, so this operation can improve the cross-person results).`
It's un clear to me what you mean by that

**Comment by LizhenWangT** [comment]
> @LizhenWangT Could you please elaborate a bit on the cross-person re-anactment. I did my driving video of input talker with faceverse so I have the renders and the uv masks. I also trained a model for 20k iterations on my target person. But I'm getting pretty bad results.
> 
> Could you help me on my way with this: `Details: As shown in Line 129-132 of FaceVerse/faceversev3_jittor/tracking_offline_cuda.py, you need to change the first 150 dims (shape parameters of another person) of the jittor tensor coeffs in Line 123 to the values (shape parameters of the source actor) in id.txt generated by FaceVerse/faceversev3_jittor/tracking_offline_cuda.py. If you are testing cross person re-enactment cases and only if the source actor's expression in the first frame is neutral expression, as shown in Line 133-134, add the first expression in exp.txt to the exp param (id and exp are coupling with each other, so this operation can improve the cross-person results).` It's un clear to me what you mean by that

If you have update the code in FaceVerse. Just add --first_frame_is_neutral and input --id_folder (the driving video also needs to be in a neutral expression in its first frame).

**Comment by Fritskee** [comment]
> > @LizhenWangT Could you please elaborate a bit on the cross-person re-anactment. I did my driving video of input talker with faceverse so I have the renders and the uv masks. I also trained a model for 20k iterations on my target person. But I'm getting pretty bad results.
> > Could you help me on my way with this: `Details: As shown in Line 129-132 of FaceVerse/faceversev3_jittor/tracking_offline_cuda.py, you need to change the first 150 dims (shape parameters of another person) of the jittor tensor coeffs in Line 123 to the values (shape parameters of the source actor) in id.txt generated by FaceVerse/faceversev3_jittor/tracking_offline_cuda.py. If you are testing cross person re-enactment cases and only if the source actor's expression in the first frame is neutral expression, as shown in Line 133-134, add the first expression in exp.txt to the exp param (id and exp are coupling with each other, so this operation can improve the cross-person results).` It's un clear to me what you mean by that
> 
> If you have update the code in FaceVerse. Just add --first_frame_is_neutral and input --id_folder (the driving video also needs to be in a neutral expression in its first frame).

That's all?
Because this part got me confused:
```you need to change the first 150 dims (shape parameters of another person) of the jittor tensor coeffs in Line 123 to the values (shape parameters of the source actor) in id.txt generated by FaceVerse/faceversev3_jittor/tracking_offline_cuda.py.```

**Comment by LizhenWangT** [comment]
> > > @LizhenWangT Could you please elaborate a bit on the cross-person re-anactment. I did my driving video of input talker with faceverse so I have the renders and the uv masks. I also trained a model for 20k iterations on my target person. But I'm getting pretty bad results.
> > > Could you help me on my way with this: `Details: As shown in Line 129-132 of FaceVerse/faceversev3_jittor/tracking_offline_cuda.py, you need to change the first 150 dims (shape parameters of another person) of the jittor tensor coeffs in Line 123 to the values (shape parameters of the source actor) in id.txt generated by FaceVerse/faceversev3_jittor/tracking_offline_cuda.py. If you are testing cross person re-enactment cases and only if the source actor's expression in the first frame is neutral expression, as shown in Line 133-134, add the first expression in exp.txt to the exp param (id and exp are coupling with each other, so this operation can improve the cross-person results).` It's un clear to me what you mean by that
> > 
> > 
> > If you have update the code in FaceVerse. Just add --first_frame_is_neutral and input --id_folder (the driving video also needs to be in a neutral expression in its first frame).
> 
> That's all? Because this part got me confused: `you need to change the first 150 dims (shape parameters of another person) of the jittor tensor coeffs in Line 123 to the values (shape parameters of the source actor) in id.txt generated by FaceVerse/faceversev3_jittor/tracking_offline_cuda.py.`

Yes, I also think its quite hard to understand, so I have updated this part into the faceverse code. But I'm too lazy, so I didn't change the readme here, I hope users can read the code and find this part by themselves lol.
