### ISSUE TITLE
Question related to face shapes for FullStyleAvatar

### ISSUE THREAD

**Issue by movingright** [LizhenWangT/StyleAvatar#17]
I see that the face shapes of the driving and target actors are relatively similar in many of yours demos. What's your intuition on how the quality will be affected when they are different? In theory, should the algorithm perform just as well?

**Comment by LizhenWangT** [comment]
This is caused by the coupling of shape and expression when tracking the 3DMM. (e.g. a big mouth image may be caused by a real big mouth or a wide smile) It works worse when the source and target actors differ significantly in appearance.

**Comment by movingright** [comment]
Got it, that's helpful, thanks @LizhenWangT :)
