### ISSUE TITLE
Missing cudnn libraries

### ISSUE THREAD

**Issue by Jerry-Master** [LizhenWangT/StyleAvatar#20]
The exe version of the preprocessing requires some cudnn libraries that are missing. Please, include them on the distributable zip or state so in the README so future users will not have to face this problem.

**Comment by LizhenWangT** [comment]
Sorry, a missing cublasLt64_11.dll file has been uploaded now. Please download the zip file again.

**Comment by Jerry-Master** [comment]
The problem is still there `INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Load FaceVerse Parameters: Tex 251 SHAPE 150 EXP 52
6: [libLoader.h::nvinfer1::rt::DynamicLibrary::DynamicLibrary::54] Error Code 6: Internal Error (Unable to load library: cudnn64_8.dll)
4: [runtime.cpp::nvinfer1::Runtime::deserializeCudaEngine::66] Error Code 4: Internal Error (Engine deserialization failed.)`

The missing DLL are the cudnn ones: 

- cudnn64_8.dll
- cudnn_adv_infer64_8.dll
- cudnn_adv_train64_8.dll
- cudnn_cnn_infer64_8.dll
- cudnn_cnn_train64_8.dll
- cudnn_ops_infer64_8.dll
- cudnn_ops_train64_8.dll

The cublas DLL was not enough to make it work.
