### ISSUE TITLE
Error when testing pretrained checkpoints

### ISSUE THREAD

**Issue by Jerry-Master** [LizhenWangT/StyleAvatar#21]
Hello, when using your pretrained checkpoints I have the following error

`load model: pretrained\tdmm_lizhen_full.pt
Traceback (most recent call last):
  File "test.py", line 57, in <module>
    g_ema.load_state_dict(ckpt["g_ema"], strict=True)
  File "C:\Users\user\anaconda3\envs\styleavatar\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DoubleStyleUnet:
        Missing key(s) in state_dict: "iwt_1.ll", "iwt_1.lh", "iwt_1.hl", "iwt_1.hh", "iwt_4.ll", "iwt_4.lh", "iwt_4.hl", "iwt_4.hh", "from_rgbs_0.0.iwt.ll", "from_rgbs_0.0.iwt.lh", "from_rgbs_0.0.iwt.hl", "from_rgbs_0.0.iwt.hh", "from_rgbs_0.0.downsample.kernel", "from_rgbs_0.0.dwt.ll", "from_rgbs_0.0.dwt.lh", "from_rgbs_0.0.dwt.hl", "from_rgbs_0.0.dwt.hh", "from_rgbs_0.0.conv.0.weight", "from_rgbs_0.0.conv.0.bias", "from_rgbs_0.1.iwt.ll", "from_rgbs_0.1.iwt.lh", "from_rgbs_0.1.iwt.hl", "from_rgbs_0.1.iwt.hh", "from_rgbs_0.1.downsample.kernel", "from_rgbs_0.1.dwt.ll", "from_rgbs_0.1.dwt.lh", "from_rgbs_0.1.dwt.hl", "from_rgbs_0.1.dwt.hh", "from_rgbs_0.1.conv.0.weight", "from_rgbs_0.1.conv.0.bias", "from_rgbs_0.2.iwt.ll", "from_rgbs_0.2.iwt.lh", "from_rgbs_0.2.iwt.hl", "from_rgbs_0.2.iwt.hh", "from_rgbs_0.2.downsample.kernel", "from_rgbs_0.2.dwt.ll", "from_rgbs_0.2.dwt.lh", "from_rgbs_0.2.dwt.hl", "from_rgbs_0.2.dwt.hh", "from_rgbs_0.2.conv.0.weight", "from_rgbs_0.2.conv.0.bias", "cond_convs_0.0.conv1.0.weight", "cond_convs_0.0.conv1.0.bias", "cond_convs_0.0.conv2.0.kernel", "cond_convs_0.0.conv2.1.weight", "cond_convs_0.0.conv2.1.bias", "cond_convs_0.1.conv1.0.weight", "cond_convs_0.1.conv1.0.bias", "cond_convs_0.1.conv2.0.kernel", "cond_convs_0.1.conv2.1.weight", "cond_convs_0.1.conv2.1.bias", "cond_convs_0.2.conv1.0.weight", "cond_convs_0.2.conv1.0.bias", "cond_convs_0.2.conv2.0.kernel", "cond_convs_0.2.conv2.1.weight", "cond_convs_0.2.conv2.1.bias", "comb_convs_0.0.0.weight", "comb_convs_0.0.0.bias", "comb_convs_0.1.0.weight", "comb_convs_0.1.0.bias", "convs_0.0.bias", "convs_0.0.conv.weight", "convs_0.0.conv.blur.kernel", "convs_0.0.conv.modulation.weight", "convs_0.0.conv.modulation.bias", "convs_0.0.noise.weight", "convs_0.1.bias", "convs_0.1.conv.weight", "convs_0.1.conv.modulation.weight", "convs_0.1.conv.modulation.bias", "convs_0.1.noise.weight", "convs_0.2.bias", "convs_0.2.conv.weight", "convs_0.2.conv.blur.kernel", "convs_0.2.conv.modulation.weight", "convs_0.2.conv.modulation.bias", "convs_0.2.noise.weight", "convs_0.3.bias", "convs_0.3.conv.weight", "convs_0.3.conv.modulation.weight", "convs_0.3.conv.modulation.bias", "convs_0.3.noise.weight", "convs_0.4.bias", "convs_0.4.conv.weight", "convs_0.4.conv.blur.kernel", "convs_0.4.conv.modulation.weight", "convs_0.4.conv.modulation.bias", "convs_0.4.noise.weight", "convs_0.5.bias", "convs_0.5.conv.weight", "convs_0.5.conv.modulation.weight", "convs_0.5.conv.modulation.bias", "convs_0.5.noise.weight", "to_rgbs_0.0.bias", "to_rgbs_0.0.iwt.ll", "to_rgbs_0.0.iwt.lh", "to_rgbs_0.0.iwt.hl", "to_rgbs_0.0.iwt.hh", "to_rgbs_0.0.upsample.kernel", "to_rgbs_0.0.dwt.ll", "to_rgbs_0.0.dwt.lh", "to_rgbs_0.0.dwt.hl", "to_rgbs_0.0.dwt.hh", "to_rgbs_0.0.conv.weight", "to_rgbs_0.0.conv.modulation.weight", "to_rgbs_0.0.conv.modulation.bias", "to_rgbs_0.1.bias", "to_rgbs_0.1.iwt.ll", "to_rgbs_0.1.iwt.lh", "to_rgbs_0.1.iwt.hl", "to_rgbs_0.1.iwt.hh", "to_rgbs_0.1.upsample.kernel", "to_rgbs_0.1.dwt.ll", "to_rgbs_0.1.dwt.lh", "to_rgbs_0.1.dwt.hl", "to_rgbs_0.1.dwt.hh", "to_rgbs_0.1.conv.weight", "to_rgbs_0.1.conv.modulation.weight", "to_rgbs_0.1.conv.modulation.bias", "to_rgbs_0.2.bias", "to_rgbs_0.2.iwt.ll", "to_rgbs_0.2.iwt.lh", "to_rgbs_0.2.iwt.hl", "to_rgbs_0.2.iwt.hh", "to_rgbs_0.2.upsample.kernel", "to_rgbs_0.2.dwt.ll", "to_rgbs_0.2.dwt.lh", "to_rgbs_0.2.dwt.hl", "to_rgbs_0.2.dwt.hh", "to_rgbs_0.2.conv.weight", "to_rgbs_0.2.conv.modulation.weight", "to_rgbs_0.2.conv.modulation.bias", "tex_up.0.bias", "tex_up.0.conv.weight", "tex_up.0.conv.blur.kernel", "tex_up.0.conv.modulation.weight", "tex_up.0.conv.modulation.bias", "tex_up.0.noise.weight", "tex_up.1.bias", "tex_up.1.conv.weight", "tex_up.1.conv.modulation.weight", "tex_up.1.conv.modulation.bias", "tex_up.1.noise.weight", "tex_up.2.bias", "tex_up.2.iwt.ll", "tex_up.2.iwt.lh", "tex_up.2.iwt.hl", "tex_up.2.iwt.hh", "tex_up.2.upsample.kernel", "tex_up.2.dwt.ll", "tex_up.2.dwt.lh", "tex_up.2.dwt.hl", "tex_up.2.dwt.hh", "tex_up.2.conv.weight", "tex_up.2.conv.modulation.weight", "tex_up.2.conv.modulation.bias", "get_mask.0.weight", "get_mask.0.bias", "cond_addition.conv1.0.weight", "cond_addition.conv1.0.bias", "cond_addition.conv2.0.kernel", "cond_addition.conv2.1.weight", "cond_addition.conv2.1.bias", "from_rgbs_1.0.iwt.ll", "from_rgbs_1.0.iwt.lh", "from_rgbs_1.0.iwt.hl", "from_rgbs_1.0.iwt.hh", "from_rgbs_1.0.downsample.kernel", "from_rgbs_1.0.dwt.ll", "from_rgbs_1.0.dwt.lh", "from_rgbs_1.0.dwt.hl", "from_rgbs_1.0.dwt.hh", "from_rgbs_1.0.conv.0.weight", "from_rgbs_1.0.conv.0.bias", "from_rgbs_1.1.iwt.ll", "from_rgbs_1.1.iwt.lh", "from_rgbs_1.1.iwt.hl", "from_rgbs_1.1.iwt.hh", "from_rgbs_1.1.downsample.kernel", "from_rgbs_1.1.dwt.ll", "from_rgbs_1.1.dwt.lh", "from_rgbs_1.1.dwt.hl", "from_rgbs_1.1.dwt.hh", "from_rgbs_1.1.conv.0.weight", "from_rgbs_1.1.conv.0.bias", "from_rgbs_1.2.iwt.ll", "from_rgbs_1.2.iwt.lh", "from_rgbs_1.2.iwt.hl", "from_rgbs_1.2.iwt.hh", "from_rgbs_1.2.downsample.kernel", "from_rgbs_1.2.dwt.ll", "from_rgbs_1.2.dwt.lh", "from_rgbs_1.2.dwt.hl", "from_rgbs_1.2.dwt.hh", "from_rgbs_1.2.conv.0.weight", "from_rgbs_1.2.conv.0.bias", "cond_convs_1.0.conv1.0.weight", "cond_convs_1.0.conv1.0.bias", "cond_convs_1.0.conv2.0.kernel", "cond_convs_1.0.conv2.1.weight", "cond_convs_1.0.conv2.1.bias", "cond_convs_1.1.conv1.0.weight", "cond_convs_1.1.conv1.0.bias", "cond_convs_1.1.conv2.0.kernel", "cond_convs_1.1.conv2.1.weight", "cond_convs_1.1.conv2.1.bias", "cond_convs_1.2.conv1.0.weight", "cond_convs_1.2.conv1.0.bias", "cond_convs_1.2.conv2.0.kernel", "cond_convs_1.2.conv2.1.weight", "cond_convs_1.2.conv2.1.bias", "comb_convs_1.0.0.weight", "comb_convs_1.0.0.bias", "comb_convs_1.1.0.weight", "comb_convs_1.1.0.bias", "comb_convs_1.2.0.weight", "comb_convs_1.2.0.bias", "convs_1.0.bias", "convs_1.0.conv.weight", "convs_1.0.conv.blur.kernel", "convs_1.0.conv.modulation.weight", "convs_1.0.conv.modulation.bias", "convs_1.0.noise.weight", "convs_1.1.bias", "convs_1.1.conv.weight", "convs_1.1.conv.modulation.weight", "convs_1.1.conv.modulation.bias", "convs_1.1.noise.weight", "convs_1.2.bias", "convs_1.2.conv.weight", "convs_1.2.conv.blur.kernel", "convs_1.2.conv.modulation.weight", "convs_1.2.conv.modulation.bias", "convs_1.2.noise.weight", "convs_1.3.bias", "convs_1.3.conv.weight", "convs_1.3.conv.modulation.weight", "convs_1.3.conv.modulation.bias", "convs_1.3.noise.weight", "convs_1.4.bias", "convs_1.4.conv.weight", "convs_1.4.conv.blur.kernel", "convs_1.4.conv.modulation.weight", "convs_1.4.conv.modulation.bias", "convs_1.4.noise.weight", "convs_1.5.bias", "convs_1.5.conv.weight", "convs_1.5.conv.modulation.weight", "convs_1.5.conv.modulation.bias", "convs_1.5.noise.weight", "convs_1.6.bias", "convs_1.6.conv.weight", "convs_1.6.conv.blur.kernel", "convs_1.6.conv.modulation.weight", "convs_1.6.conv.modulation.bias", "convs_1.6.noise.weight", "convs_1.7.bias", "convs_1.7.conv.weight", "convs_1.7.conv.modulation.weight", "convs_1.7.conv.modulation.bias", "convs_1.7.noise.weight", "convs_1.8.bias", "convs_1.8.conv.weight", "convs_1.8.conv.blur.kernel", "convs_1.8.conv.modulation.weight", "convs_1.8.conv.modulation.bias", "convs_1.8.noise.weight", "convs_1.9.bias", "convs_1.9.conv.weight", "convs_1.9.conv.modulation.weight", "convs_1.9.conv.modulation.bias", "convs_1.9.noise.weight", "convs_1.10.bias", "convs_1.10.conv.weight", "convs_1.10.conv.blur.kernel", "convs_1.10.conv.modulation.weight", "convs_1.10.conv.modulation.bias", "convs_1.10.noise.weight", "convs_1.11.bias", "convs_1.11.conv.weight", "convs_1.11.conv.modulation.weight", "convs_1.11.conv.modulation.bias", "convs_1.11.noise.weight", "to_rgbs_1.0.bias", "to_rgbs_1.0.iwt.ll", "to_rgbs_1.0.iwt.lh", "to_rgbs_1.0.iwt.hl", "to_rgbs_1.0.iwt.hh", "to_rgbs_1.0.upsample.kernel", "to_rgbs_1.0.dwt.ll", "to_rgbs_1.0.dwt.lh", "to_rgbs_1.0.dwt.hl", "to_rgbs_1.0.dwt.hh", "to_rgbs_1.0.conv.weight", "to_rgbs_1.0.conv.modulation.weight", "to_rgbs_1.0.conv.modulation.bias", "to_rgbs_1.1.bias", "to_rgbs_1.1.iwt.ll", "to_rgbs_1.1.iwt.lh", "to_rgbs_1.1.iwt.hl", "to_rgbs_1.1.iwt.hh", "to_rgbs_1.1.upsample.kernel", "to_rgbs_1.1.dwt.ll", "to_rgbs_1.1.dwt.lh", "to_rgbs_1.1.dwt.hl", "to_rgbs_1.1.dwt.hh", "to_rgbs_1.1.conv.weight", "to_rgbs_1.1.conv.modulation.weight", "to_rgbs_1.1.conv.modulation.bias", "to_rgbs_1.2.bias", "to_rgbs_1.2.iwt.ll", "to_rgbs_1.2.iwt.lh", "to_rgbs_1.2.iwt.hl", "to_rgbs_1.2.iwt.hh", "to_rgbs_1.2.upsample.kernel", "to_rgbs_1.2.dwt.ll", "to_rgbs_1.2.dwt.lh", "to_rgbs_1.2.dwt.hl", "to_rgbs_1.2.dwt.hh", "to_rgbs_1.2.conv.weight", "to_rgbs_1.2.conv.modulation.weight", "to_rgbs_1.2.conv.modulation.bias", "to_rgbs_1.3.bias", "to_rgbs_1.3.iwt.ll", "to_rgbs_1.3.iwt.lh", "to_rgbs_1.3.iwt.hl", "to_rgbs_1.3.iwt.hh", "to_rgbs_1.3.upsample.kernel", "to_rgbs_1.3.dwt.ll", "to_rgbs_1.3.dwt.lh", "to_rgbs_1.3.dwt.hl", "to_rgbs_1.3.dwt.hh", "to_rgbs_1.3.conv.weight", "to_rgbs_1.3.conv.modulation.weight", "to_rgbs_1.3.conv.modulation.bias", "to_rgbs_1.4.bias", "to_rgbs_1.4.iwt.ll", "to_rgbs_1.4.iwt.lh", "to_rgbs_1.4.iwt.hl", "to_rgbs_1.4.iwt.hh", "to_rgbs_1.4.upsample.kernel", "to_rgbs_1.4.dwt.ll", "to_rgbs_1.4.dwt.lh", "to_rgbs_1.4.dwt.hl", "to_rgbs_1.4.dwt.hh", "to_rgbs_1.4.conv.weight", "to_rgbs_1.4.conv.modulation.weight", "to_rgbs_1.4.conv.modulation.bias", "to_rgbs_1.5.bias", "to_rgbs_1.5.iwt.ll", "to_rgbs_1.5.iwt.lh", "to_rgbs_1.5.iwt.hl", "to_rgbs_1.5.iwt.hh", "to_rgbs_1.5.upsample.kernel", "to_rgbs_1.5.dwt.ll", "to_rgbs_1.5.dwt.lh", "to_rgbs_1.5.dwt.hl", "to_rgbs_1.5.dwt.hh", "to_rgbs_1.5.conv.weight", "to_rgbs_1.5.conv.modulation.weight", "to_rgbs_1.5.conv.modulation.bias".
        Unexpected key(s) in state_dict: "from_rgbs.0.iwt.ll", "from_rgbs.0.iwt.lh", "from_rgbs.0.iwt.hl", "from_rgbs.0.iwt.hh", "from_rgbs.0.downsample.kernel", "from_rgbs.0.dwt.ll", "from_rgbs.0.dwt.lh", "from_rgbs.0.dwt.hl", "from_rgbs.0.dwt.hh", "from_rgbs.0.conv.0.weight", "from_rgbs.0.conv.0.bias", "from_rgbs.1.iwt.ll", "from_rgbs.1.iwt.lh", "from_rgbs.1.iwt.hl", "from_rgbs.1.iwt.hh", "from_rgbs.1.downsample.kernel", "from_rgbs.1.dwt.ll", "from_rgbs.1.dwt.lh", "from_rgbs.1.dwt.hl", "from_rgbs.1.dwt.hh", "from_rgbs.1.conv.0.weight", "from_rgbs.1.conv.0.bias", "from_rgbs.2.iwt.ll", "from_rgbs.2.iwt.lh", "from_rgbs.2.iwt.hl", "from_rgbs.2.iwt.hh", "from_rgbs.2.downsample.kernel", "from_rgbs.2.dwt.ll", "from_rgbs.2.dwt.lh", "from_rgbs.2.dwt.hl", "from_rgbs.2.dwt.hh", "from_rgbs.2.conv.0.weight", "from_rgbs.2.conv.0.bias", "cond_convs.0.conv1.0.weight", "cond_convs.0.conv1.0.bias", "cond_convs.0.conv2.0.kernel", "cond_convs.0.conv2.1.weight", "cond_convs.0.conv2.1.bias", "cond_convs.1.conv1.0.weight", "cond_convs.1.conv1.0.bias", "cond_convs.1.conv2.0.kernel", "cond_convs.1.conv2.1.weight", "cond_convs.1.conv2.1.bias", "cond_convs.2.conv1.0.weight", "cond_convs.2.conv1.0.bias", "cond_convs.2.conv2.0.kernel", "cond_convs.2.conv2.1.weight", "cond_convs.2.conv2.1.bias", "comb_convs.0.0.weight", "comb_convs.0.0.bias", "comb_convs.1.0.weight", "comb_convs.1.0.bias", "comb_convs.2.0.weight", "comb_convs.2.0.bias", "convs.0.bias", "convs.0.conv.weight", "convs.0.conv.blur.kernel", "convs.0.conv.modulation.weight", "convs.0.conv.modulation.bias", "convs.0.noise.weight", "convs.1.bias", "convs.1.conv.weight", "convs.1.conv.modulation.weight", "convs.1.conv.modulation.bias", "convs.1.noise.weight", "convs.2.bias", "convs.2.conv.weight", "convs.2.conv.blur.kernel", "convs.2.conv.modulation.weight", "convs.2.conv.modulation.bias", "convs.2.noise.weight", "convs.3.bias", "convs.3.conv.weight", "convs.3.conv.modulation.weight", "convs.3.conv.modulation.bias", "convs.3.noise.weight", "convs.4.bias", "convs.4.conv.weight", "convs.4.conv.blur.kernel", "convs.4.conv.modulation.weight", "convs.4.conv.modulation.bias", "convs.4.noise.weight", "convs.5.bias", "convs.5.conv.weight", "convs.5.conv.modulation.weight", "convs.5.conv.modulation.bias", "convs.5.noise.weight", "convs.6.bias", "convs.6.conv.weight", "convs.6.conv.blur.kernel", "convs.6.conv.modulation.weight", "convs.6.conv.modulation.bias", "convs.6.noise.weight", "convs.7.bias", "convs.7.conv.weight", "convs.7.conv.modulation.weight", "convs.7.conv.modulation.bias", "convs.7.noise.weight", "convs.8.bias", "convs.8.conv.weight", "convs.8.conv.blur.kernel", "convs.8.conv.modulation.weight", "convs.8.conv.modulation.bias", "convs.8.noise.weight", "convs.9.bias", "convs.9.conv.weight", "convs.9.conv.modulation.weight", "convs.9.conv.modulation.bias", "convs.9.noise.weight", "convs.10.bias", "convs.10.conv.weight", "convs.10.conv.blur.kernel", "convs.10.conv.modulation.weight", "convs.10.conv.modulation.bias", "convs.10.noise.weight", "convs.11.bias", "convs.11.conv.weight", "convs.11.conv.modulation.weight", "convs.11.conv.modulation.bias", "convs.11.noise.weight", "to_rgbs.0.bias", "to_rgbs.0.iwt.ll", "to_rgbs.0.iwt.lh", "to_rgbs.0.iwt.hl", "to_rgbs.0.iwt.hh", "to_rgbs.0.upsample.kernel", "to_rgbs.0.dwt.ll", "to_rgbs.0.dwt.lh", "to_rgbs.0.dwt.hl", "to_rgbs.0.dwt.hh", "to_rgbs.0.conv.weight", "to_rgbs.0.conv.modulation.weight", "to_rgbs.0.conv.modulation.bias", "to_rgbs.1.bias", "to_rgbs.1.iwt.ll", "to_rgbs.1.iwt.lh", "to_rgbs.1.iwt.hl", "to_rgbs.1.iwt.hh", "to_rgbs.1.upsample.kernel", "to_rgbs.1.dwt.ll", "to_rgbs.1.dwt.lh", "to_rgbs.1.dwt.hl", "to_rgbs.1.dwt.hh", "to_rgbs.1.conv.weight", "to_rgbs.1.conv.modulation.weight", "to_rgbs.1.conv.modulation.bias", "to_rgbs.2.bias", "to_rgbs.2.iwt.ll", "to_rgbs.2.iwt.lh", "to_rgbs.2.iwt.hl", "to_rgbs.2.iwt.hh", "to_rgbs.2.upsample.kernel", "to_rgbs.2.dwt.ll", "to_rgbs.2.dwt.lh", "to_rgbs.2.dwt.hl", "to_rgbs.2.dwt.hh", "to_rgbs.2.conv.weight", "to_rgbs.2.conv.modulation.weight", "to_rgbs.2.conv.modulation.bias", "to_rgbs.3.bias", "to_rgbs.3.iwt.ll", "to_rgbs.3.iwt.lh", "to_rgbs.3.iwt.hl", "to_rgbs.3.iwt.hh", "to_rgbs.3.upsample.kernel", "to_rgbs.3.dwt.ll", "to_rgbs.3.dwt.lh", "to_rgbs.3.dwt.hl", "to_rgbs.3.dwt.hh", "to_rgbs.3.conv.weight", "to_rgbs.3.conv.modulation.weight", "to_rgbs.3.conv.modulation.bias", "to_rgbs.4.bias", "to_rgbs.4.iwt.ll", "to_rgbs.4.iwt.lh", "to_rgbs.4.iwt.hl", "to_rgbs.4.iwt.hh", "to_rgbs.4.upsample.kernel", "to_rgbs.4.dwt.ll", "to_rgbs.4.dwt.lh", "to_rgbs.4.dwt.hl", "to_rgbs.4.dwt.hh", "to_rgbs.4.conv.weight", "to_rgbs.4.conv.modulation.weight", "to_rgbs.4.conv.modulation.bias", "to_rgbs.5.bias", "to_rgbs.5.iwt.ll", "to_rgbs.5.iwt.lh", "to_rgbs.5.iwt.hl", "to_rgbs.5.iwt.hh", "to_rgbs.5.upsample.kernel", "to_rgbs.5.dwt.ll", "to_rgbs.5.dwt.lh", "to_rgbs.5.dwt.hl", "to_rgbs.5.dwt.hh", "to_rgbs.5.conv.weight", "to_rgbs.5.conv.modulation.weight", "to_rgbs.5.conv.modulation.bias".`

Any clue about what is happening? The command I used was `python test.py --render_dir D:\TRASPASOS\styleavatar\code\results\lizhen_20210318_1536\render --uv_dir D:\TRASPASOS\styleavatar\code\results\lizhen_20210318_1536\uv --ckpt pretrained\tdmm_lizhen_full.pt --save_dir output\lizhen``, it gives a similar error with the tdmm_lizhen.pt checkpoint.

**Comment by Jerry-Master** [comment]
However, the renders and UV all seem fine.
![000010](https://github.com/LizhenWangT/StyleAvatar/assets/34888496/20dd8aa4-a9f8-4c7a-8638-2150ead493a0)
![000010](https://github.com/LizhenWangT/StyleAvatar/assets/34888496/69b8a5bf-f80a-4bef-b8aa-46b5bec2a0c2)

**Comment by LizhenWangT** [comment]
Please use the python preprocessing code for the python pretrained model or exe preprocessing file for the exe pretrained model.

**Comment by Jerry-Master** [comment]
Yes, I thought the python code would be compatible with the exe preprocessing. How can I use the exe to work with the pretrained ckpt?

**Comment by LizhenWangT** [comment]
You can try this ckpt:
```
model 1 (trained on lizhen's video, exe version): https://drive.google.com/file/d/1f_iVravaL4oi9TC1kIld1d7pQg1VZw_B/view?usp=sharing
```

**Comment by Jerry-Master** [comment]
Now it works! Thanks for clarifying.

![000010](https://github.com/LizhenWangT/StyleAvatar/assets/34888496/30a5a45e-b518-4875-bd9e-a9f9d811a329)

**Comment by zain3211** [comment]
PS C:\Users\IT-LINKS\Desktop\style\StyleAvatar\styleavatar>
                                                          > python test.py --render_dir "C:\Users\IT-LINKS\Desktop\style\StyleAvatar\styleavatar\input_directory" --uv_dir "path-to-dataset/uv" --ckpt "C:\Users\IT-LINKS\Desktop\style\StyleAvatar\styleavatar\pretrained\lizhen_full_python.pt" --save_dir "C:\Users\IT-LINKS\Desktop\style\StyleAvatar\styleavatar\output"
load model: C:\Users\IT-LINKS\Desktop\style\StyleAvatar\styleavatar\pretrained\lizhen_full_python.pt
C:\Users\IT-LINKS\miniconda3\Lib\site-packages\torch\nn\functional.py:3809: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
Traceback (most recent call last):
  File "C:\Users\IT-LINKS\Desktop\style\StyleAvatar\styleavatar\test.py", line 57, in <module>
    test(args, g_ema, device)
  File "C:\Users\IT-LINKS\Desktop\style\StyleAvatar\styleavatar\test.py", line 15, in test
    test_list = os.listdir(args.render_dir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\IT-LINKS\\Desktop\\style\\StyleAvatar\\styleavatar\\input_directory'       
PS C:\Users\IT-LINKS\Desktop\style\StyleAvatar\styleavatar>   how to specify paths please tell
