### ISSUE TITLE
Error with cublas64_11.dll when running faceverse.exe

### ISSUE THREAD

**Issue by Fritskee** [LizhenWangT/StyleAvatar#32]
**Description:**
When I attempt to run faceverse.exe, I encounter the following error related to the CUDA library:
```
procedure entry point cublasLt_for_cublas_TST could not be located in the dynamic link library C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\cublas64_11.dll
```

**Steps to Reproduce:**
Installed required .dll files in the application directory.
Ran faceverse.exe.
Expected Behavior:
faceverse.exe runs without any errors.

**Actual Behavior:**
Received the aforementioned error related to cublas64_11.dll.

**Environment:**
OS: Windows 10
GPU: Nvidia A4500
CUDA Version: v11.8

**Additional Context:**
I encountered this issue after I added the missing .dll files to the application's folder as suggested in the documentation.
Any assistance or guidance on resolving this issue would be appreciated.

**Comment by LizhenWangT** [comment]
It can only be used on sm_86 GPUs (RTX 3060 3070 3080 3090 3090ti).
And note this: `If you miss some cudnn dll files, please download them in [Google Drive](https://drive.google.com/file/d/1lGYgwZ3_vLAlbEoNIzmR4H5WwwPNQcIa/view?usp=sharing) or [Baidu Netdisk](https://pan.baidu.com/s/1nVfBu3wRQVgWDMCvyvFwSQ?pwd=bsm6) password: bsm6.`

**Comment by Fritskee** [comment]
Hi LizhenWangT, thanks for the response. Seems like I'm out of luck then because of the GPU. 
I indeed added the .dll files already, so that wasn't the issue.
