### ISSUE TITLE
论文中的小错误

### ISSUE THREAD

**Issue by kiritosaac** [LizhenWangT/StyleAvatar#34]
![image](https://github.com/LizhenWangT/StyleAvatar/assets/101173839/1dbfd365-4261-4784-9224-3110f2e5b838)
下面的标注应该是3.1,3.2,3.3才对吧？

**Comment by LizhenWangT** [comment]
感谢指正，之前有个overview，为了省篇幅删掉了，但论文终稿很久之前已经交了ORZ
