### ISSUE TITLE
rendering texture + uv vertex color

### ISSUE THREAD

**Issue by alchemician** [LizhenWangT/StyleAvatar#4]
Thanks a lot for this - great work! You mention "We will crop the video, then render the tracked FaceVerse model with texture and uv vertex colors"; where is this part of the code? 

I am trying to run the pre-trained model with the output from faceverse but the results are bad and i believe it's because it's not rendering the texture and uv vertex color

**Comment by LizhenWangT** [comment]
If you want to change the texture of faceverse, you need to add --use_dr on Linux system.

If you only want to run it for StyleAvatar. You don't need to change the texture. StyleAvatar can run for any texture. Note that there is no code prepared for the preprocessing of the pretrained model now, and you neeed to use this code to train your own model.

**Comment by alchemician** [comment]
Yes I am trying to use this code to train my own model but there isn't much info on preprocessing data for TDMM. I tried to do it myself using methodology described in the paper but eventually got stuck at this error when training the TDMM and can't figure out a solution for it. Let me know if you have any idea. 

  0%|                                                                                         | 0/800000 [00:00<?, ?it/s]Input Shape: torch.Size([3, 8192])
Weight Shape: torch.Size([512, 8192])
Input Shape: torch.Size([3, 512])
Weight Shape: torch.Size([512, 8192])
  0%|                                                                                         | 0/800000 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 374, in <module>
    train(args, loader, generator, discriminator, g_ema, g_optim, d_optim, device)
  File "train.py", line 167, in train
    real_pred = discriminator(torch.cat([real_img, cond_img], dim=1)) 
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/StyleAvatar/styleunet/networks/discriminator.py", line 76, in forward
    out = self.final_linear(out)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/StyleAvatar/styleunet/networks/modules_for_discriminator.py", line 151, in forward
    out = F.linear(input, self.weight * self.scale)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x512 and 8192x512)

**Comment by LizhenWangT** [comment]
What's your resolution of input images and please let me see your command of
`python tracking_offline_cuda.py ...` and `python train.py ...`

I can not reproduce your bug by running
```python .\tracking_offline_cuda.py --input ..\example\videos\test.mp4 --res_folder .\output\styleavatar --save_for_styleavatar```
in faceversev3_jittor folder

and then run
```python train.py --batch 3 --mode 3 ..\..\FaceVerse\faceversev3_jittor\output\styleavatar\```
in styleunet folder

**Comment by LizhenWangT** [comment]
It seems that you are using a wrong image resolution for input images.
Did you add `--mode 3` when you train your own model?

**Comment by alchemician** [comment]
Resolution is 256X256; (I just used a video from the project page demo and ran it through faceverse then cropped it to get it to 256X256). 

This is the train.py log:
~/StyleAvatar/styleunet$ python train.py --batch 3 --mode 3 StyleAvatar/styleunet/Dataset
  0%|                                                                                         | 0/800000 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 374, in <module>
    train(args, loader, generator, discriminator, g_ema, g_optim, d_optim, device)
  File "train.py", line 167, in train
    real_pred = discriminator(torch.cat([real_img, cond_img], dim=1)) 
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/StyleAvatar/styleunet/networks/discriminator.py", line 76, in forward
    out = self.final_linear(out)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/StyleAvatar/styleunet/networks/modules_for_discriminator.py", line 149, in forward
    out = F.linear(input, self.weight * self.scale)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x512 and 8192x512)

**Comment by LizhenWangT** [comment]
How do you run faceverse? I think you don't need to crop the video by yourself. Just run like this
https://github.com/LizhenWangT/StyleAvatar/issues/4#issuecomment-1628205140

**Comment by LizhenWangT** [comment]
The output image should be 1024x1024 (real portrait image) and the input image should be 256x256 (faceverse rendering).

**Comment by alchemician** [comment]
Ah still getting the same error; this is the image and render folder from Faceverse:
Image: 
![image](https://github.com/LizhenWangT/StyleAvatar/assets/93725624/9c785cf5-bf6d-47a9-9f87-9f6e766a2371)

render:
![image](https://github.com/LizhenWangT/StyleAvatar/assets/93725624/7fed18c3-e3e0-470b-a6fb-b1d6e4cb0e24)

Getting this error:
(myenv) ubuntu@104-171-202-235:~/StyleAvatar/styleunet$ python train.py --batch 3 --mode 3 ..\..\FaceVerse\faceversev3_jittor\output\styleavatar\
> 
  0%|                                                                                         | 0/800000 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 374, in <module>
    train(args, loader, generator, discriminator, g_ema, g_optim, d_optim, device)
  File "train.py", line 167, in train
    real_pred = discriminator(torch.cat([real_img, cond_img], dim=1)) 
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/StyleAvatar/styleunet/networks/discriminator.py", line 76, in forward
    out = self.final_linear(out)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/StyleAvatar/styleunet/networks/modules_for_discriminator.py", line 149, in forward
    out = F.linear(input, self.weight * self.scale)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x512 and 8192x512)


Thanks a lot in advance for your help - not too sure how to proceed

**Comment by LizhenWangT** [comment]
I think you still need to check your image input to the discriminator. Obviously `RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x512 and 8192x512)` should be 3x512x16 and 8192x512, which means your input image is 4 times smaller than 1024. You seem to use a 256 image as the input of discriminator. Please check your code or folder name again.

**Comment by LizhenWangT** [comment]
What's your args.output_size for mode 3 now? It should be 1024. I can not reproduce this bug. Or you can clone this repo again if your code has been modified.

**Comment by alchemician** [comment]
@LizhenWangT - I just reinstalled everything and it worked, thanks! The issue was with the preprocessing that I was doing. However, a new issue came up... The checkpoint keys are different than the one of the pretrained model so i can't load the model for testing. See below:
**Model I trained:**
print(checkpoint.keys())
​
dict_keys(['g', 'd', 'g_ema', 'g_optim', 'd_optim', 'args'])

**Pretrained model**
odict_keys(['mapping.0.weight', 'mapping.0.bias', 'mapping.2.weight', 'mapping.2.bias', 'mapping.4.weight', 'mapping.4.bias', 'mapping.6.weight', 'mapping.6.bias', 'dwt.ll', 'dwt.lh', 'dwt.hl', 'dwt.hh', 'from_rgbs.0.iwt.ll', 'from_rgbs.0.iwt.lh', 'from_rgbs.0.iwt.hl', 'from_rgbs.0.iwt.hh', 'from_rgbs.0.downsample.kernel', 'from_rgbs.0.dwt.ll', 'from_rgbs.0.dwt.lh', 'from_rgbs.0.dwt.hl', 'from_rgbs.0.dwt.hh', 'from_rgbs.0.conv.0.weight', 'from_rgbs.0.conv.0.bias', 'from_rgbs.1.iwt.ll', 'from_rgbs.1.iwt.lh', 'from_rgbs.1.iwt.hl', 'from_rgbs.1.iwt.hh', 'from_rgbs.1.downsample.kernel', 'from_rgbs.1.dwt.ll', 'from_rgbs.1.dwt.lh', 'from_rgbs.1.dwt.hl', 'from_rgbs.1.dwt.hh', 'from_rgbs.1.conv.0.weight', 'from_rgbs.1.conv.0.bias', 'from_rgbs.2.iwt.ll', 'from_rgbs.2.iwt.lh', 'from_rgbs.2.iwt.hl', 'from_rgbs.2.iwt.hh', 'from_rgbs.2.downsample.kernel', 'from_rgbs.2.dwt.ll', 'from_rgbs.2.dwt.lh', 'from_rgbs.2.dwt.hl', 'from_rgbs.2.dwt.hh', 'from_rgbs.2.conv.0.weight', 'from_rgbs.2.conv.0.bias', 'cond_convs.0.conv1.0.weight', 'cond_convs.0.conv1.0.bias', 'cond_convs.0.conv2.0.kernel', 'cond_convs.0.conv2.1.weight', 'cond_convs.0.conv2.1.bias', 'cond_convs.1.conv1.0.weight', 'cond_convs.1.conv1.0.bias', 'cond_convs.1.conv2.0.kernel', 'cond_convs.1.conv2.1.weight', 'cond_convs.1.conv2.1.bias', 'cond_convs.2.conv1.0.weight', 'cond_convs.2.conv1.0.bias', 'cond_convs.2.conv2.0.kernel', 'cond_convs.2.conv2.1.weight', 'cond_convs.2.conv2.1.bias', 'comb_convs.0.0.weight', 'comb_convs.0.0.bias', 'comb_convs.1.0.weight', 'comb_convs.1.0.bias', 'comb_convs.2.0.weight', 'comb_convs.2.0.bias', 'convs.0.bias', 'convs.0.conv.weight', 'convs.0.conv.blur.kernel', 'convs.0.conv.modulation.weight', 'convs.0.conv.modulation.bias', 'convs.0.noise.weight', 'convs.1.bias', 'convs.1.conv.weight', 'convs.1.conv.modulation.weight', 'convs.1.conv.modulation.bias', 'convs.1.noise.weight', 'convs.2.bias', 'convs.2.conv.weight', 'convs.2.conv.blur.kernel', 'convs.2.conv.modulation.weight', 'convs.2.conv.modulation.bias', 'convs.2.noise.weight', 'convs.3.bias', 'convs.3.conv.weight', 'convs.3.conv.modulation.weight', 'convs.3.conv.modulation.bias', 'convs.3.noise.weight', 'convs.4.bias', 'convs.4.conv.weight', 'convs.4.conv.blur.kernel', 'convs.4.conv.modulation.weight', 'convs.4.conv.modulation.bias', 'convs.4.noise.weight', 'convs.5.bias', 'convs.5.conv.weight', 'convs.5.conv.modulation.weight', 'convs.5.conv.modulation.bias', 'convs.5.noise.weight', 'convs.6.bias', 'convs.6.conv.weight', 'convs.6.conv.blur.kernel', 'convs.6.conv.modulation.weight', 'convs.6.conv.modulation.bias', 'convs.6.noise.weight', 'convs.7.bias', 'convs.7.conv.weight', 'convs.7.conv.modulation.weight', 'convs.7.conv.modulation.bias', 'convs.7.noise.weight', 'convs.8.bias', 'convs.8.conv.weight', 'convs.8.conv.blur.kernel', 'convs.8.conv.modulation.weight', 'convs.8.conv.modulation.bias', 'convs.8.noise.weight', 'convs.9.bias', 'convs.9.conv.weight', 'convs.9.conv.modulation.weight', 'convs.9.conv.modulation.bias', 'convs.9.noise.weight', 'convs.10.bias', 'convs.10.conv.weight', 'convs.10.conv.blur.kernel', 'convs.10.conv.modulation.weight', 'convs.10.conv.modulation.bias', 'convs.10.noise.weight', 'convs.11.bias', 'convs.11.conv.weight', 'convs.11.conv.modulation.weight', 'convs.11.conv.modulation.bias', 'convs.11.noise.weight', 'to_rgbs.0.bias', 'to_rgbs.0.iwt.ll', 'to_rgbs.0.iwt.lh', 'to_rgbs.0.iwt.hl', 'to_rgbs.0.iwt.hh', 'to_rgbs.0.upsample.kernel', 'to_rgbs.0.dwt.ll', 'to_rgbs.0.dwt.lh', 'to_rgbs.0.dwt.hl', 'to_rgbs.0.dwt.hh', 'to_rgbs.0.conv.weight', 'to_rgbs.0.conv.modulation.weight', 'to_rgbs.0.conv.modulation.bias', 'to_rgbs.1.bias', 'to_rgbs.1.iwt.ll', 'to_rgbs.1.iwt.lh', 'to_rgbs.1.iwt.hl', 'to_rgbs.1.iwt.hh', 'to_rgbs.1.upsample.kernel', 'to_rgbs.1.dwt.ll', 'to_rgbs.1.dwt.lh', 'to_rgbs.1.dwt.hl', 'to_rgbs.1.dwt.hh', 'to_rgbs.1.conv.weight', 'to_rgbs.1.conv.modulation.weight', 'to_rgbs.1.conv.modulation.bias', 'to_rgbs.2.bias', 'to_rgbs.2.iwt.ll', 'to_rgbs.2.iwt.lh', 'to_rgbs.2.iwt.hl', 'to_rgbs.2.iwt.hh', 'to_rgbs.2.upsample.kernel', 'to_rgbs.2.dwt.ll', 'to_rgbs.2.dwt.lh', 'to_rgbs.2.dwt.hl', 'to_rgbs.2.dwt.hh', 'to_rgbs.2.conv.weight', 'to_rgbs.2.conv.modulation.weight', 'to_rgbs.2.conv.modulation.bias', 'to_rgbs.3.bias', 'to_rgbs.3.iwt.ll', 'to_rgbs.3.iwt.lh', 'to_rgbs.3.iwt.hl', 'to_rgbs.3.iwt.hh', 'to_rgbs.3.upsample.kernel', 'to_rgbs.3.dwt.ll', 'to_rgbs.3.dwt.lh', 'to_rgbs.3.dwt.hl', 'to_rgbs.3.dwt.hh', 'to_rgbs.3.conv.weight', 'to_rgbs.3.conv.modulation.weight', 'to_rgbs.3.conv.modulation.bias', 'to_rgbs.4.bias', 'to_rgbs.4.iwt.ll', 'to_rgbs.4.iwt.lh', 'to_rgbs.4.iwt.hl', 'to_rgbs.4.iwt.hh', 'to_rgbs.4.upsample.kernel', 'to_rgbs.4.dwt.ll', 'to_rgbs.4.dwt.lh', 'to_rgbs.4.dwt.hl', 'to_rgbs.4.dwt.hh', 'to_rgbs.4.conv.weight', 'to_rgbs.4.conv.modulation.weight', 'to_rgbs.4.conv.modulation.bias', 'to_rgbs.5.bias', 'to_rgbs.5.iwt.ll', 'to_rgbs.5.iwt.lh', 'to_rgbs.5.iwt.hl', 'to_rgbs.5.iwt.hh', 'to_rgbs.5.upsample.kernel', 'to_rgbs.5.dwt.ll', 'to_rgbs.5.dwt.lh', 'to_rgbs.5.dwt.hl', 'to_rgbs.5.dwt.hh', 'to_rgbs.5.conv.weight', 'to_rgbs.5.conv.modulation.weight', 'to_rgbs.5.conv.modulation.bias', 'iwt.ll', 'iwt.lh', 'iwt.hl', 'iwt.hh'])

I tried changing 
g_ema.load_state_dict(ckpt, strict=True) to strict=False but then the results are very off...

Any suggestion? Is this normal?

**Comment by LizhenWangT** [comment]
Tell me which model you are using. You need to use the model for exactly the same mode for testing. For pretraining, the model trained for mode 0 1 2 can not be used for mode 3.

**Comment by LizhenWangT** [comment]
It seems you are using the checkpoint for superresolution, you can only use it by
```python test.py --input_dir input/superresolution --ckpt .\pretrained\superresolution_full.pt --save_dir output/superresolution --mode 1```

**Comment by alchemician** [comment]
and this for testing:
python test.py --input_dir input/tdmm_full --ckpt pretrained/tdmm_full.pt --save_dir output/tdmm_full.pt --mode 3

**Comment by LizhenWangT** [comment]
I can not reproduce your bug again. I use a model trained by
`python train.py --batch 3 --mode 3 ../../FaceVerse/faceversev3_jittor/output/styleavatar/`
It works very well when using
`python test.py --input_dir input/tdmm --ckpt logs/checkpoint/tdmm_005000.pt --save_dir output/tdmm --mode 3`

I do not provide a file named `tdmm_full.pt`. Is there any thing wrong with your code or the file `tdmm_full.pt`. The provided pretrained model `tdmm_lizhen.pt` only contains the key of 'g_ema' for smaller file size.

**Comment by alchemician** [comment]
I got it to work finally; I had to change the testing code as follow:
from:` g_ema.load_state_dict(ckpt, strict=True) ` 
to: ` g_ema.load_state_dict(ckpt("g_emma"), strict=False)`.
The reason why I did this is because in train.py it does this https://github.com/LizhenWangT/StyleAvatar/blob/34ea9dd987c7c18195023edbeca43aad71f98e93/styleunet/train.py#L330C9-L330C9

This worked very well for same person reenactment but didn't work for cross person re-enactment. I changed the ID as follow: 
I added these 2 lines
`id_params = np.loadtxt("/home/ubuntu/FaceVerse/faceversev3_jittor/output/video/id.txt")
      coeffs[:,:150] = id_params`
 right before this: 
 https://github.com/LizhenWangT/FaceVerse/blob/ee3d8b8032519deab04591fa6960b9642d295660/faceversev3_jittor/tracking_offline_cuda.py#L123
 
 Thanks again for the help, almost there! Will give your work the citation and support that it deserves

**Comment by LizhenWangT** [comment]
Yes, the exp parameters are somewhat coupling with the id parameters. If there is a significant difference in appearance between the source actor and the target actor or they have many different expressions. StyleAvatar can not work very well in these cases.

**Comment by alchemician** [comment]
got it - great paper and great code nevertheless - very good job!
