### ISSUE TITLE
Should we replace the id params in faceverse or add?

### ISSUE THREAD

**Issue by alchemician** [LizhenWangT/StyleAvatar#8]
Hello author,

In this line should you add the id coeffs to existing id coeffs or just replace them?https://github.com/LizhenWangT/FaceVerse/blob/24b86858b99035b54bce8514521df53af7100f9d/faceversev3_jittor/tracking_offline_cuda.py#L132C33-L132C33

**Comment by alchemician** [comment]
Also, [this](https://github.com/LizhenWangT/FaceVerse/blob/24b86858b99035b54bce8514521df53af7100f9d/faceversev3_jittor/tracking_offline_cuda.py#L134C22-L134C83) line should be like below I believe,

coeffs[:, self.fvm.id_dims:self.fvm.id_dims+self.fvm.exp_dims] += exp_fisrt

**Comment by LizhenWangT** [comment]
Thanks for the comments! You are right. It should be replace and `self.fvm.id_dims+self.fvm.exp_dims`.
